[workspace]
members = [
    "app",
    "arpeggiator",
    "chord",
    "cmrt-runtime",
    "config-editor-lib",
    "core-lib",
    "daw",
    "daw-client-lib",
    "grid-sequencer",
    "history",
    "keyboard",
    "loop-browser",
    "loop-browser-domain",
    "loop-domain",
    "notepad",
    "offline-render",
    "realtime-play",
    "rubberband-ffi",
    "surge-patches",
    "tui-core",
]
resolver = "2"
