[package]
name = "cmrt-keyboard"
version = "0.1.0"
edition = "2021"

[dependencies]
cmrt-chord = { path = "../chord" }
cmrt-realtime-play = { path = "../realtime-play" }
cmrt-runtime = { path = "../cmrt-runtime" }
cmrt-patches = { path = "../patches" }
cmrt-tui-core = { path = "../tui-core" }
anyhow = "1"
crossterm = "0.29"
rand = "0.10"
ratatui = "0.30"
serde = { version = "1", features = ["derive"] }
ratatui-textarea = { version = "0.9", features = ["crossterm"] }

[dev-dependencies]
serde_json = "1"
