[package]
name = "cmrt-keyboard"
version = "0.1.0"
edition = "2021"

[dependencies]
cmrt-chord = { path = "../chord" }
cmrt-realtime-play = { path = "../realtime-play" }
cmrt-runtime = { path = "../cmrt-runtime" }
cmrt-tui-core = { path = "../tui-core" }
anyhow = "1"
crossterm = "0.28"
rand = "0.8"
ratatui = "0.28"
serde = { version = "1", features = ["derive"] }
tui-textarea = { version = "0.6", features = ["crossterm"] }

[dev-dependencies]
serde_json = "1"
