pub(crate) mod clipboard;
pub mod config;
pub(crate) mod config_editor;
pub mod daw;
pub(crate) mod fast_midi_ipc;
pub(crate) mod generate;
pub mod history;
pub mod logging;
pub mod loop_browser;
pub(crate) use cmrt_loop_domain::{loop_wav_analysis, loop_waveform};
pub(crate) mod mixer_overlay;
pub(crate) mod offline_render;
pub(crate) mod patches;
pub(crate) mod random;
pub(crate) mod realtime_play;
pub(crate) mod screen_switch;
pub mod server;
pub(crate) mod sound_check_guide;
#[cfg(test)]
pub(crate) mod test_utils;
pub(crate) mod text_input;
pub mod tui;
pub(crate) mod ui_theme;
pub mod ui_utils;
pub mod updater;
pub mod voicing_cache_builder;
pub(crate) mod voicing_sources;
pub(crate) mod wav_io;
